version: '1.0'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - internal
    volumes:
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./var/www/html:/var/www/html
    depends_on:
      - php
  php:
    build: ./docker/php
    container_name: php
    restart: always
    networks:
      - internal
    volumes:
      - ./var/www/html:/var/www/html
      - "./usr/local/etc/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    networks:
      - internal
    environment:
      - MYSQL_DATABASE=bt2_login
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=t3i
      - MYSQL_PASSWORD=t3i
    ports:
      - "3306:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"


networks:
  internal:
    driver: bridge